# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboarder < Formula
  desc ""
  homepage ""
  version "1.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.3.0/onboarder_1.3.0_Darwin_arm64.tar.gz"
      sha256 "fae5643217afadc1cc75bf53c520e4c9e52ddd95d7243456a11c52842c016c18"

      def install
        bin.install "onboarder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.3.0/onboarder_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "232b18d43cffdb70b4b82a7ac5d7c7bad8c42772e2286bd4a4f39e881d650cec"

      def install
        bin.install "onboarder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.3.0/onboarder_1.3.0_Linux_arm64.tar.gz"
      sha256 "c60132adebee4a908f27a82b5a26d98b70b07b2c8f418a2ada47ee3107fbd501"

      def install
        bin.install "onboarder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.3.0/onboarder_1.3.0_Linux_x86_64.tar.gz"
      sha256 "6db46ff2a94ed49b4c10f36018291289d3fb17e1deb348687e494032375ea002"

      def install
        bin.install "onboarder"
      end
    end
  end
end
