# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Onboarder < Formula
  desc ""
  homepage ""
  version "1.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.1.0/onboarder_1.1.0_Darwin_arm64.tar.gz"
      sha256 "62fef4e656dfd3e2b35fb8da3055147f09eb0052cd0c48078c1c4a4216b69636"

      def install
        bin.install "onboarder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.1.0/onboarder_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "9a730357916cb7449536b76fa557615abc32efdebeac73aa5186029f7f7c6bf6"

      def install
        bin.install "onboarder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.1.0/onboarder_1.1.0_Linux_arm64.tar.gz"
      sha256 "b43dd0603ce55d9f6f8edbeebd5ed0ea9c595be78e2a3cb65d2e07233b9f3880"

      def install
        bin.install "onboarder"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/terakilobyte/onboarder/releases/download/v1.1.0/onboarder_1.1.0_Linux_x86_64.tar.gz"
      sha256 "722e0209ff4beecac31c9c43040be02478107819507718cddcdfb764882778d5"

      def install
        bin.install "onboarder"
      end
    end
  end
end
